// Localizes system notifications (title + message) generated by the DB.
// User-authored content (ask names, nudge response messages) is passed through.
//
// The DB stores notification text in English. We re-derive a localized
// version from `type` + the raw message, extracting dynamic params via
// regex. If parsing fails for any reason, we fall back to the raw text
// so nothing ever disappears.

const NUDGE_RESPONSE_FALLBACK = /^Update sent$/

// Title is mostly static per type. Two types embed sender/child in the
// title itself — handled separately below via regex extraction.
const TITLE_KEY_BY_TYPE = {
  pickup_confirmed: 'notif_title_pickup_confirmed',
  dropoff_confirmed: 'notif_title_dropoff_confirmed',
  expense_pending: 'notif_title_expense_pending',
  expense_added: 'notif_title_expense_added',
  task_assigned: 'notif_title_task_assigned',
  task_started: 'notif_title_task_started',
  task_completed: 'notif_title_task_completed',
  task_failed: 'notif_title_task_failed',
  task_rejected: 'notif_title_task_rejected',
  ask_received: 'notif_title_ask_received',
  ask_accepted: 'notif_title_ask_accepted',
  ask_rejected: 'notif_title_ask_rejected',
  understanding_proposed: 'notif_title_understanding_proposed',
  understanding_accepted: 'notif_title_understanding_accepted',
  understanding_rejected: 'notif_title_understanding_rejected',
  custody_override_requested: 'notif_title_custody_override_requested',
  custody_override_approved: 'notif_title_custody_override_approved',
  custody_override_rejected: 'notif_title_custody_override_rejected',
  pickup_escalated: 'notif_title_handoff_escalated',
  dropoff_escalated: 'notif_title_handoff_escalated',
  dropoff_expected: 'notif_title_dropoff_expected',
  unexpected_pickup: 'notif_title_unexpected_pickup',
}

const HANDOFF_ACTION_KEYS = {
  pickup: 'notif_handoff_action_pickup',
  dropoff: 'notif_handoff_action_dropoff',
}

function handoffActionLabel(action, t) {
  const key = HANDOFF_ACTION_KEYS[action]
  const localized = key ? t(key) : null
  return localized && localized !== key ? localized : action
}

function interp(template, params) {
  return template.replace(/\{(\w+)\}/g, (_, k) => (params[k] ?? ''))
}

// Some entity titles/subjects embedded inside notification messages are
// generated by the system (event generator, default understandings) and
// stored in English. Translate them when we recognize them; leave user-
// authored titles untouched.
const SYSTEM_TITLE_KEYS = {
  'Custody Handoff - Pickup': 'sysTitle_custodyHandoffPickup',
  'Custody Handoff - Dropoff': 'sysTitle_custodyHandoffDropoff',
  'Expense Sharing Rules': 'sysTitle_expenseSharingRules',
  'Expense Sharing Agreement': 'sysTitle_expenseSharingAgreement',
}

function localizeSystemTitle(value, t) {
  if (!value) return value
  const key = SYSTEM_TITLE_KEYS[value]
  if (!key) return value
  const localized = t(key)
  return localized && localized !== key ? localized : value
}

function isGenericHandoffTitle(value) {
  return value === 'Custody Handoff - Pickup' || value === 'Custody Handoff - Dropoff'
}

// Returns null if no localized form can be produced (caller uses raw).
// `extras` may carry resolved context the message can't derive from `raw`
// alone — currently { childName } looked up from the related event.
function localizeMessage(type, raw, t, extras = {}) {
  if (!raw || typeof raw !== 'string') return null

  switch (type) {
    case 'pickup_confirmed': {
      const m = raw.match(/^(.*) was picked up$/)
      if (!m) return null
      return interp(t('notif_msg_pickup_confirmed'), { child: m[1] })
    }
    case 'dropoff_confirmed': {
      const m = raw.match(/^(.*?) was dropped off(?: at (.*))?$/)
      if (!m) return null
      const key = m[2] ? 'notif_msg_dropoff_at' : 'notif_msg_dropoff'
      return interp(t(key), { child: m[1], notes: m[2] || '' })
    }
    case 'expense_pending':
    case 'expense_added': {
      const m = raw.match(/^(.*) - ([\d.,]+) (\S+?)(?: \((.+)\))?$/)
      if (!m) return null
      const base = interp(t('notif_msg_expense_base'), {
        title: m[1], amount: m[2], currency: m[3]
      })
      if (m[4]) return interp(t('notif_msg_expense_with_reason'), { base, reason: m[4] })
      return base
    }
    case 'task_assigned': {
      const m = raw.match(/^(.*) \(assigned by (.*)\)$/)
      if (!m) return null
      return interp(t('notif_msg_task_assigned'), { name: m[1], creator: m[2] })
    }
    case 'task_started': {
      const m = raw.match(/^(.*) \(by (.*)\)$/)
      if (!m) return null
      return interp(t('notif_msg_task_started'), { name: m[1], actor: m[2] })
    }
    case 'task_completed': {
      const m = raw.match(/^(.*) marked as done$/)
      if (!m) return null
      return interp(t('notif_msg_task_completed'), { name: m[1] })
    }
    case 'task_failed': {
      const m = raw.match(/^(.*) could not be completed$/)
      if (!m) return null
      return interp(t('notif_msg_task_failed'), { name: m[1] })
    }
    case 'task_rejected':
    case 'ask_rejected': {
      const m = raw.match(/^(.*) was declined$/)
      if (!m) return null
      return interp(t('notif_msg_was_declined'), { name: m[1] })
    }
    case 'ask_accepted': {
      const m = raw.match(/^(.*) was approved$/)
      if (!m) return null
      return interp(t('notif_msg_was_approved'), { name: m[1] })
    }
    case 'ask_received': {
      // message is user-authored ask name — leave as-is
      return raw
    }
    case 'understanding_proposed': {
      const m = raw.match(/^New understanding proposal: (.*)$/)
      if (!m) return null
      return interp(t('notif_msg_understanding_proposed'), {
        subject: localizeSystemTitle(m[1], t),
      })
    }
    case 'understanding_accepted': {
      const m = raw.match(/^"(.*)" was approved$/)
      if (!m) return null
      return interp(t('notif_msg_understanding_accepted'), {
        subject: localizeSystemTitle(m[1], t),
      })
    }
    case 'understanding_rejected': {
      const m = raw.match(/^"(.*)" was not approved$/)
      if (!m) return null
      return interp(t('notif_msg_understanding_rejected'), {
        subject: localizeSystemTitle(m[1], t),
      })
    }
    case 'custody_override_requested': {
      const m = raw.match(/^(.*) requests custody change: (.*?) - (.*)$/)
      if (!m) return null
      return interp(t('notif_msg_custody_override_requested'), {
        requester: m[1], from: m[2], to: m[3]
      })
    }
    case 'custody_override_approved': {
      const m = raw.match(/^Your custody change \((.*?) - (.*?)\) was approved$/)
      if (!m) return null
      return interp(t('notif_msg_custody_override_approved'), { from: m[1], to: m[2] })
    }
    case 'custody_override_rejected': {
      const m = raw.match(/^Your custody change \((.*?) - (.*?)\) was not approved$/)
      if (!m) return null
      return interp(t('notif_msg_custody_override_rejected'), { from: m[1], to: m[2] })
    }
    case 'nudge_request': {
      const m = raw.match(/^(.*) misses (.*) and would love a quick update!$/)
      if (!m) return null
      return interp(t('notif_msg_nudge_request'), { sender: m[1], child: m[2] })
    }
    case 'nudge_response': {
      // The DB stores: TRIM(mood + ' ' + user_message), or 'Update sent' when both empty.
      if (NUDGE_RESPONSE_FALLBACK.test(raw)) return t('notif_msg_nudge_update_sent')
      // user-authored content — pass through
      return raw
    }
    // pickup_missed type is used for both pickup AND dropoff missed events;
    // the action verb is embedded in the message text itself.
    case 'pickup_missed':
    case 'dropoff_missed': {
      const m = raw.match(/^Please confirm (pickup|dropoff) for (.*)$/)
      if (!m) return null
      const action = m[1]
      const child = extras.childName || ''
      const generic = isGenericHandoffTitle(m[2])
      // Generic auto-generated event title → drop it entirely.
      // Custom event title → include it for context.
      let key
      if (action === 'pickup') {
        key = generic
          ? (child ? 'notif_msg_pickup_missed_child' : 'notif_msg_pickup_missed_generic')
          : (child ? 'notif_msg_pickup_missed_child_at' : 'notif_msg_pickup_missed_at')
      } else {
        key = generic
          ? (child ? 'notif_msg_dropoff_missed_child' : 'notif_msg_dropoff_missed_generic')
          : (child ? 'notif_msg_dropoff_missed_child_at' : 'notif_msg_dropoff_missed_at')
      }
      return interp(t(key), { child, title: m[2] })
    }
    case 'pickup_escalated':
    case 'dropoff_escalated': {
      const m = raw.match(/^(pickup|dropoff) not confirmed for (.*) - please check$/)
      if (!m) return null
      const action = m[1]
      const child = extras.childName || ''
      const generic = isGenericHandoffTitle(m[2])
      let key
      if (action === 'pickup') {
        key = generic
          ? (child ? 'notif_msg_pickup_escalated_child' : 'notif_msg_pickup_escalated_generic')
          : (child ? 'notif_msg_pickup_escalated_child_at' : 'notif_msg_pickup_escalated_at')
      } else {
        key = generic
          ? (child ? 'notif_msg_dropoff_escalated_child' : 'notif_msg_dropoff_escalated_generic')
          : (child ? 'notif_msg_dropoff_escalated_child_at' : 'notif_msg_dropoff_escalated_at')
      }
      return interp(t(key), { child, title: m[2] })
    }
    case 'dropoff_expected': {
      const m = raw.match(/^Have you dropped off (.*) at (.*) yet\?$/)
      if (!m) return null
      return interp(t('notif_msg_dropoff_expected'), {
        child: m[1],
        title: localizeSystemTitle(m[2], t),
      })
    }
    case 'unexpected_pickup': {
      const m = raw.match(/^(.*) was picked up on your custody day$/)
      if (!m) return null
      return interp(t('notif_msg_unexpected_pickup'), { child: m[1] })
    }
    default:
      return null
  }
}

function localizeTitle(type, rawTitle, t) {
  // Static-title types via type→key map
  const key = TITLE_KEY_BY_TYPE[type]
  if (key) {
    const localized = t(key)
    // useI18n's t() returns the key itself when missing — guard against that
    return localized && localized !== key ? localized : rawTitle
  }

  // Dynamic titles: extract sender/child via regex
  if (type === 'nudge_request' && rawTitle) {
    const m = rawTitle.match(/^(.*) is thinking of (.*)$/)
    if (m) return interp(t('notif_title_nudge_request'), { sender: m[1], child: m[2] })
  }
  if (type === 'nudge_response' && rawTitle) {
    const m = rawTitle.match(/^(.*) sent an update!$/)
    if (m) return interp(t('notif_title_nudge_response'), { sender: m[1] })
  }
  if ((type === 'pickup_missed' || type === 'dropoff_missed') && rawTitle) {
    const m = rawTitle.match(/^(pickup|dropoff) not confirmed$/)
    if (m) {
      const key = m[1] === 'pickup' ? 'notif_title_pickup_missed' : 'notif_title_dropoff_missed'
      return t(key)
    }
  }

  return rawTitle
}

export function formatNotificationTitle(notification, t) {
  if (!notification) return ''
  return localizeTitle(notification.type, notification.title, t) || notification.title || ''
}

export function formatNotificationMessage(notification, t, extras = {}) {
  if (!notification) return ''
  const localized = localizeMessage(notification.type, notification.message, t, extras)
  return localized || notification.message || ''
}

// Pull a child name out of the dashboard store for notifications whose
// related entity is an event. Returns '' if it can't be resolved — the
// formatter then falls back to a child-less template.
export function resolveNotificationExtras(notification, dashboardStore) {
  if (!notification || !dashboardStore) return {}
  const needsEvent = ['pickup_missed', 'dropoff_missed', 'pickup_escalated', 'dropoff_escalated']
    .includes(notification.type)
  if (!needsEvent || notification.related_entity_type !== 'event' || !notification.related_entity_id) {
    return {}
  }
  const event = (dashboardStore.events || []).find(e => e.id === notification.related_entity_id)
  if (!event) return {}
  const childId = event.event_children?.[0]?.child_id
  if (!childId) return {}
  const child = (dashboardStore.children || []).find(c => c.id === childId)
  return child ? { childName: child.name } : {}
}

export function formatRelativeTime(timestamp, t) {
  const date = new Date(timestamp || Date.now())
  const now = new Date()
  const diff = now - date
  const minutes = Math.floor(diff / 60000)
  if (minutes < 1) return t('notif_time_now')
  if (minutes < 60) return interp(t('notif_time_minutes'), { n: minutes })
  const hours = Math.floor(diff / 3600000)
  if (hours < 24) return interp(t('notif_time_hours'), { n: hours })
  const days = Math.floor(diff / 86400000)
  if (days === 1) return t('yesterday')
  if (days < 7) return interp(t('notif_time_days'), { n: days })
  return date.toLocaleDateString()
}
